/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientSide.GUI_Interface;

import ClientSide.ClientAPI;

import javax.swing.JOptionPane;

/**
 *
 * @author sarthakmanna
 */
public class Client_GUI extends javax.swing.JFrame {

    private final ClientAPI CLIENT_API;
    public String selfUsername;

    /**
     * Creates new form ClientSide
     */
    public Client_GUI(ClientAPI api, String whoAmI) throws Exception {
        CLIENT_API = api;
        selfUsername = whoAmI;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        rbOnline = new javax.swing.JRadioButton();
        cbOnline = new javax.swing.JComboBox<>();
        rbAll = new javax.swing.JRadioButton();
        cbAll = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tfSelected = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taChat = new javax.swing.JTextArea();
        tfSend = new javax.swing.JTextField();
        btSend = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        rbFriends = new javax.swing.JRadioButton();
        cbFriends = new javax.swing.JComboBox<>();
        cbAutoScroll = new javax.swing.JCheckBox();
        lbSelf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GOSSup");
        setLocationByPlatform(true);
        setResizable(false);

        rbOnline.setSelected(true);
        rbOnline.setText("Online Peers");
        rbOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOnlineActionPerformed(evt);
            }
        });

        cbOnline.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOnlineActionPerformed(evt);
            }
        });

        rbAll.setText("All Peers");
        rbAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAllActionPerformed(evt);
            }
        });

        cbAll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAll.setEnabled(false);
        cbAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAllActionPerformed(evt);
            }
        });

        jLabel1.setText("Selected Peer");

        tfSelected.setEditable(false);

        jLabel2.setText("Chat History");

        taChat.setEditable(false);
        taChat.setColumns(20);
        taChat.setRows(5);
        jScrollPane1.setViewportView(taChat);

        tfSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSendActionPerformed(evt);
            }
        });

        btSend.setText("Send");
        btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendActionPerformed(evt);
            }
        });

        rbFriends.setText("Friends");
        rbFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFriendsActionPerformed(evt);
            }
        });

        cbFriends.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFriends.setEnabled(false);
        cbFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFriendsActionPerformed(evt);
            }
        });

        cbAutoScroll.setText("Auto Scroll");

        lbSelf.setText("You: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbSelf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfSend)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btSend))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbAutoScroll))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(rbFriends, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(rbAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(rbOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cbOnline, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbAll, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbFriends, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(tfSelected))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbSelf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbOnline)
                                        .addComponent(cbOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbAll)
                                        .addComponent(cbAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbFriends)
                                        .addComponent(cbFriends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(cbAutoScroll))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btSend))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void rbOnlineActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        rbOnline.setSelected(true);
        rbAll.setSelected(false);
        rbFriends.setSelected(false);

        cbOnline.setEnabled(true);
        cbAll.setEnabled(false);
        cbFriends.setEnabled(false);

        try {
            tfSelected.setText(cbOnline.getSelectedItem().toString());
        } catch (Exception e) {
            tfSelected.setText("");
        }
    }

    private void rbAllActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        rbOnline.setSelected(false);
        rbAll.setSelected(true);
        rbFriends.setSelected(false);

        cbOnline.setEnabled(false);
        cbAll.setEnabled(true);
        cbFriends.setEnabled(false);

        try {
            tfSelected.setText(cbAll.getSelectedItem().toString());
        } catch (Exception e) {
            tfSelected.setText("");
        }
    }

    private void rbFriendsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        rbOnline.setSelected(false);
        rbAll.setSelected(false);
        rbFriends.setSelected(true);

        cbOnline.setEnabled(false);
        cbAll.setEnabled(false);
        cbFriends.setEnabled(true);

        try {
            tfSelected.setText(cbFriends.getSelectedItem().toString());
        } catch (Exception e) {
            tfSelected.setText("");
        }
    }

    private void cbOnlineActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cbAllActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cbFriendsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btSendActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try { sendButton(); } catch (Exception e) {}
    }

    private void tfSendActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try { sendButton(); } catch (Exception e) {}
    }

    void sendButton() throws Exception {
        if (tfSend.getText().equals("")) return;

        if (tfSelected.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a valid username !!!",
                    "Receiver's username is not specified", JOptionPane.ERROR_MESSAGE);
        } else {
            CLIENT_API.sendMessage(tfSelected.getText(), tfSend.getText());
        }

        tfSend.setText("");
    }

    void startClient_GUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BackgroundUpdate(cbOnline, cbAll, cbFriends,
                            tfSelected, taChat, cbAutoScroll, CLIENT_API).start();

                    lbSelf.setText("You are \'" + selfUsername + "\'");

                    setLocationRelativeTo(null);
                    setVisible(true);
                } catch (Exception e) {
                    System.out.println("Cannot connect to the server !!!!");

                    JOptionPane.showMessageDialog(null, "Cannot connect to the server !!!",
                            "Connection Error", JOptionPane.ERROR_MESSAGE);

                    System.exit(1);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btSend;
    private javax.swing.JComboBox<String> cbAll;
    private javax.swing.JCheckBox cbAutoScroll;
    private javax.swing.JComboBox<String> cbFriends;
    private javax.swing.JComboBox<String> cbOnline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbSelf;
    private javax.swing.JRadioButton rbAll;
    private javax.swing.JRadioButton rbFriends;
    private javax.swing.JRadioButton rbOnline;
    private javax.swing.JTextArea taChat;
    private javax.swing.JTextField tfSelected;
    private javax.swing.JTextField tfSend;
    // End of variables declaration                   
}